using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;

public class HowEasy
{
	public int pointVal(string param0)
	{
		Regex r = new Regex(@"\b([A-Za-z]+)\b(?!\.)");
		
		Match m = r.Match(param0);
		int numberOfLetters = 0, numberOfWords = 0;
		while(m.Success) {
			numberOfLetters += m.Groups[0].Value.Length;
			numberOfWords++;
			m = m.NextMatch();
		} 
		double avgWordLength = numberOfWords == 0 ? 0 : ((double)numberOfLetters)/numberOfWords;
		
		int returnRate = avgWordLength <= 3 ? 250 : (avgWordLength >= 6 ? 1000 : 500 );
		Console.WriteLine(avgWordLength + " - " + param0 + " - " + returnRate);
		return returnRate;
	}

	#region Testing code generated by KawigiEdit
	[STAThread]
	public static void Main(string[] args)
	{
		int answer, desiredAnswer;
		bool errors = false;
		DateTime time;

				
		HowEasy h = new HowEasy();
		errors = h.pointVal("This is a problem statement") != 500;
		if (!errors) errors = h.pointVal("523hi.") != 250;
		if (!errors) errors = h.pointVal("Implement a class H5 which contains some method.") != 500;
		if (!errors) errors = h.pointVal(" no9 . wor7ds he8re. hj..") != 250;
		
		
		if (errors)
			Console.WriteLine("Some of the test cases had errors :-(");
		else
			Console.WriteLine("You're a stud (at least on the test data)! :-D ");
	}
	#endregion

}
//Powered by [KawigiEdit] 2.0!
