using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;

public class PalindromesCount
{
	public int count(string A, string B)
	{
		int result =0;
		for(int i=0; i<=A.Length; i++)
		{
			string newString = A.Insert(i, B);
			Char[] chars = newString.ToCharArray();
			Array.Reverse(chars);
			if(newString ==  new String(chars))
				result++;
		}
		
		return result;
	}

	#region Testing code generated by KawigiEdit
	[STAThread]
	public static void Main(string[] args)
	{
		int answer, desiredAnswer;
		bool errors = false;
		DateTime time;
		
		time = DateTime.Now;
		answer = new PalindromesCount().count("aba", "b");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = 2;
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t" + desiredAnswer);
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new PalindromesCount().count("aa", "a");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = 3;
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t" + desiredAnswer);
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new PalindromesCount().count("aca", "bb");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = 0;
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t" + desiredAnswer);
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new PalindromesCount().count("abba", "abba");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = 3;
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t" + desiredAnswer);
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new PalindromesCount().count("topcoder", "coder");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = 0;
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t" + desiredAnswer);
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		
		
		if (errors)
			Console.WriteLine("Some of the test cases had errors :-(");
		else
			Console.WriteLine("You're a stud (at least on the test data)! :-D ");
	}
	#endregion

}
//Powered by [KawigiEdit] 2.0!
