using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;

public class RouteIntersection
{
	public string isValid(int N, int[] coords, string moves)
	{
		if(coords.Length > 0)
		{	
			int[][] movesInCoords = new int[moves.Length + 1][];
			
			movesInCoords[0] = new int[N];
			
			for(int i=1; i < movesInCoords.Length; i++)
			{
				int[] moveInCoords = new int[N];
				movesInCoords[i - 1].CopyTo(moveInCoords, 0);
				moveInCoords[coords[i - 1] - 1] += (moves[i -1] == '+' ? 1 : -1);
				movesInCoords[i] = moveInCoords;
				
				//Console.Write("(");
				//foreach(int g in moveInCoords)
				//	Console.Write("{0},", g);
				//Console.WriteLine(")");
				
				for(int j=i - 2; j >= 0; j--)
				{
					bool isAllEquals = true;
					for(int h=0; h < N; h++)
					{
						if(moveInCoords[h] != movesInCoords[j][h])
						{
							isAllEquals = false;
							break;
						}
					}
					
					if(isAllEquals)
						return "NOT VALID";
				}
			}
		}	
		
		return "VALID";
	}

	#region Testing code generated by KawigiEdit
	[STAThread]
	public static void Main(string[] args)
	{
		string answer, desiredAnswer;
		bool errors = false;
		DateTime time;
		
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(1, new int[]{1}, "+");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(2, new int[]{1,2,1,2}, "++--");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "NOT VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(3, new int[]{1,2,3,1,2}, "+++--");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(344447, new int[]{132,51717,628,344447,628,51717,344447,2}, "+-++-+--");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "NOT VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(1, new int[]{1,1}, "+-");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "NOT VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new RouteIntersection().isValid(990630, new int[]{833196,524568,361663,108056,28026,824639,269315,440977,440977,765458,988451,242440,948414,130873,773990,765458,130873,28026,853121,553636,581069,82254,735536,833196,898562,898562,940783,988451,540613,317306,623194,940783,571384,988451,108056,514374,97664}, "--+---+-+++-+-+---++-++-+---+-+--+-++");
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "NOT VALID";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		
		
		if (errors)
			Console.WriteLine("Some of the test cases had errors :-(");
		else
			Console.WriteLine("You're a stud (at least on the test data)! :-D ");
	}
	#endregion

}
//Powered by [KawigiEdit] 2.0!
