using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;

public class Time
{
	public string whatTime(int seconds)
	{
		int h = (int)Math.Floor((double)(seconds/3600)),
			m = (int)Math.Floor((double)((seconds%3600)/60)),
			s = (seconds%3600)%60;
		return string.Format("{0}:{1}:{2}", h, m, s);
	}

	#region Testing code generated by KawigiEdit
	[STAThread]
	public static void Main(string[] args)
	{
		string answer, desiredAnswer;
		bool errors = false;
		DateTime time;
		
		time = DateTime.Now;
		answer = new Time().whatTime(0);
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "0:0:0";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new Time().whatTime(3661);
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "1:1:1";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new Time().whatTime(5436);
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "1:30:36";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		time = DateTime.Now;
		answer = new Time().whatTime(86399);
		Console.WriteLine("Time: " + (DateTime.Now-time).TotalSeconds + " seconds");
		desiredAnswer = "23:59:59";
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t\"" + answer + "\"");
		Console.WriteLine("Desired answer:");
		Console.WriteLine("\t\"" + desiredAnswer + "\"");
		if (answer != desiredAnswer)
		{
			errors = true;
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else
			Console.WriteLine("Match :-)");
		Console.WriteLine();
		
		
		if (errors)
			Console.WriteLine("Some of the test cases had errors :-(");
		else
			Console.WriteLine("You're a stud (at least on the test data)! :-D ");
	}
	#endregion

}
//Powered by [KawigiEdit] 2.0!
